module.exports.prospects = [
  {
    first_name: "Fedor",
    last_name: "Gordeev",
    position: "D",
    shoots: "L",
    dob: "1999-01-27",
    round: 5,
    pick: 141,
    draft_year: 2017,
    player_id: 7146,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7146&category=seasonstats",
    games_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7146&category=gamebygame",
    league: "OHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=273797"
  },
  {
    first_name: "Eemeli",
    last_name: "Rasanen",
    position: "D",
    shoots: "R",
    dob: "1999-03-06",
    round: 2,
    pick: 59,
    draft_year: 2017,
    player_id: 31190,
    profile_url: "https://en.khl.ru/players/31190/",
    league: "KHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=302228"
  },
  {
    first_name: "Ryan",
    last_name: "McGregor",
    position: "C",
    shoots: "L",
    dob: "1999-01-29",
    round: 6,
    pick: 172,
    draft_year: 2017,
    player_id: 7117,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7117&category=seasonstats",
    games_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7117&category=gamebygame",
    league: "OHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=289231"
  },
  {
    first_name: "Timothy",
    last_name: "Liljegren",
    position: "D",
    shoots: "R",
    dob: "1999-04-20",
    round: 1,
    pick: 17,
    draft_year: 2017,
    player_id: 6893,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6893&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    games_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6893&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=224910"
  },
  {
    first_name: "Jeremy",
    last_name: "Bracco",
    position: "RW",
    shoots: "R",
    dob: "1997-03-17",
    round: 2,
    pick: 61,
    draft_year: 2015,
    player_id: 6891,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6891&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=197800"
  },
  {
    first_name: "Adam",
    last_name: "Brooks",
    position: "C",
    shoots: "L",
    dob: "1996-05-06",
    round: 4,
    pick: 92,
    draft_year: 2016,
    player_id: 6888,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6888&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=120202"
  },
  {
    first_name: "Dmytro",
    last_name: "Timashov",
    position: "LW",
    shoots: "L",
    dob: "1996-10-01",
    round: 5,
    pick: 125,
    draft_year: 2015,
    player_id: 6445,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6445&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=115161"
  },
  {
    first_name: "Andrew",
    last_name: "Nielsen",
    position: "D",
    shoots: "L",
    dob: "1996-11-13",
    round: 3,
    pick: 65,
    draft_year: 2015,
    player_id: 6296,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6296&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=131262"
  },
  {
    first_name: "Calle",
    last_name: "Rosen",
    position: "D",
    shoots: "L",
    dob: "1994-02-02",
    round: null,
    pick: null,
    draft_year: null,
    player_id: 6917,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6917&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=37021"
  },
  {
    first_name: "Andreas",
    last_name: "Borgman",
    position: "D",
    shoots: "L",
    dob: "1995-06-18",
    round: null,
    pick: null,
    draft_year: null,
    player_id: 6966,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6966&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=85683"
  },
  {
    first_name: "Martin",
    last_name: "Dzierkals",
    position: "LW",
    shoots: "L",
    dob: "1997-04-04",
    round: 3,
    pick: 68,
    draft_year: 2015,
    player_id: 23319,
    profile_url: "https://en.khl.ru/players/23319/",
    league: "KHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=239362"
  },
  {
    first_name: "J.J.",
    last_name: "Piccinich",
    position: "RW",
    shoots: "R",
    dob: "1996-06-12",
    round: 4,
    pick: 103,
    draft_year: 2014,
    player_id: 7307,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7307&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=191113"
  },
  {
    first_name: "Yegor",
    last_name: "Korshkov",
    position: "RW",
    shoots: "L",
    dob: "1996-07-10",
    round: 2,
    pick: 31,
    draft_year: 2016,
    player_id: 20766,
    profile_url: "https://en.khl.ru/players/20766/",
    league: "KHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=176637"
  },
  {
    first_name: "Carl",
    last_name: "Grundstrom",
    position: "LW",
    shoots: "L",
    dob: "1997-12-01",
    round: 2,
    pick: 57,
    draft_year: 2016,
    player_id: 6788,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6788&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=113516"
  },
  {
    first_name: "Pierre",
    last_name: "Engvall",
    position: "W",
    shoots: "L",
    dob: "1996-05-31",
    round: 7,
    pick: 188,
    draft_year: 2014,
    player_id: 6761,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6761&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=147720"
  },
  {
    first_name: "Vladislav",
    last_name: "Kara",
    position: "C",
    shoots: "L",
    dob: "1998-04-20",
    round: 4,
    pick: 124,
    draft_year: 2017,
    player_id: 22888,
    profile_url: "https://en.khl.ru/players/22888/",
    league: "KHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=322627"
  },
  {
    first_name: "Nikolai",
    last_name: "Chebykin",
    position: "W",
    shoots: "L",
    dob: "1997-08-01",
    round: 7,
    pick: 182,
    draft_year: 2016,
    player_id: 22161,
    profile_url: "http://www.vhlru.ru/en/players/22161/",
    league: "VHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=300931"
  },
  {
    first_name: "Vladimir",
    last_name: "Bobylyov",
    position: "W",
    shoots: "L",
    dob: "1997-04-18",
    round: 5,
    pick: 122,
    draft_year: 2016,
    player_id: 21313,
    profile_url: "https://en.khl.ru/players/21313/",
    league: "KHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=268059"
  },
  {
    first_name: "Dakota",
    last_name: "Joshua",
    position: "C",
    shoots: "L",
    dob: "1996-05-15",
    round: 5,
    pick: 128,
    draft_year: 2014,
    player_id: 29891,
    profile_url: "https://www.collegehockeynews.com/players/career/Dakota-Joshua/29891",
    league: "NCAA",
    ep_url: "http://www.eliteprospects.com/player.php?player=194948"
  },
  {
    first_name: "James",
    last_name: "Greenway",
    position: "D",
    shoots: "L",
    dob: "1998-04-27",
    round: 3,
    pick: 72,
    draft_year: 2016,
    player_id: 31877,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=245&site_id=0&key=e828f89b243dc43f&client_code=ushl&league_id=&lang=en&statsType=standard&callback=json",
    league: "USHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=226438"
  },
  {
    first_name: "Jesper",
    last_name: "Lindgren",
    position: "D",
    shoots: "R",
    dob: "1997-05-19",
    round: 4,
    pick: 95,
    draft_year: 2015,
    player_id: 100025980,
    profile_url: "http://liiga.fi/pelaajat/100025980/lindgren-jesper",
    league: "Liiga",
    ep_url: "http://www.eliteprospects.com/player.php?player=187806"
  },
  {
    first_name: "Rasmus",
    last_name: "Sandin",
    position: "D",
    shoots: "L",
    dob: "2000-03-07",
    round: 1,
    pick: 29,
    draft_year: 2018,
    player_id: 7852,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7852&category=seasonstats",
    league: "OHL",
    ep_url: "https://www.eliteprospects.com/player/289453/rasmus-sandin"
  },
  {
    first_name: "Sean",
    last_name: "Durzi",
    position: "D",
    shoots: "R",
    dob: "1998-10-21",
    round: 2,
    pick: 52,
    draft_year: 2018,
    player_id: 7174,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7174&category=seasonstats",
    games_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7174&category=gamebygame",
    league: "OHL",
    ep_url: "https://www.eliteprospects.com/player/268973/sean-durzi"
  },
  {
    first_name: "Semyon",
    last_name: "Der-Arguchintsev",
    position: "C",
    shoots: "R",
    dob: "2000-09-15",
    round: 3,
    pick: 76,
    draft_year: 2018,
    player_id: 7484,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7484&category=seasonstats",
    games_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=7484&category=gamebygame",
    league: "OHL",
    ep_url: "https://www.eliteprospects.com/player/315260/semyon-der-arguchintsev"
  },
  {
    first_name: "Riley",
    last_name: "Stotts",
    position: "C",
    shoots: "L",
    dob: "2000-01-05",
    round: 3,
    pick: 83,
    draft_year: 2018,
    player_id: 27355,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=41b145a848f4bd67&fmt=json&client_code=whl&lang=en&player_id=27355&category=seasonstats",
    games_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=41b145a848f4bd67&fmt=json&client_code=whl&lang=en&player_id=27355&category=gamebygame",
    league: "WHL",
    ep_url: "https://www.eliteprospects.com/player/201715/riley-stotts"
  },
  {
    first_name: "Mac",
    last_name: "Hollowell",
    position: "D",
    shoots: "R",
    dob: "1998-09-26",
    round: 4,
    pick: 118,
    draft_year: 2018,
    player_id: 6948,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=6948&category=seasonstats",
    games_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=2976319eb44abe94&fmt=json&client_code=ohl&lang=en&player_id=6948&category=gamebygame",
    league: "OHL",
    ep_url: "https://www.eliteprospects.com/player/267652/mac-hollowell"
  },
  {
    first_name: "Filip",
    last_name: "Kral",
    position: "D",
    shoots: "L",
    dob: "1999-10-20",
    round: 5,
    pick: 149,
    draft_year: 2018,
    player_id: 27960,
    profile_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=41b145a848f4bd67&fmt=json&client_code=whl&lang=en&player_id=27960&category=seasonstats",
    games_url: "http://lscluster.hockeytech.com/feed/?feed=modulekit&view=player&key=41b145a848f4bd67&fmt=json&client_code=whl&lang=en&player_id=27355&category=gamebygame",
    league: "WHL",
    ep_url: "https://www.eliteprospects.com/player/247241/filip-kral"
  },
  {
    first_name: "Pontus",
    last_name: "Holmberg",
    position: "LW",
    shoots: "L",
    dob: "1999-03-09",
    round: 6,
    pick: 156,
    draft_year: 2018,
    player_id: 0,
    profile_url: "https://www.shl.se/lag/fe02-fe02mf1FN__vaxjo-lakers/qTK-4a8Y9mMrn__pontus-holmberg/statistics",
    league: "SHL",
    ep_url: "https://www.eliteprospects.com/player/265859/pontus-holmberg"
  },
  {
    first_name: "Semyon",
    last_name: "Kizimov",
    position: "LW",
    shoots: "L",
    dob: "2000-01-19",
    round: 7,
    pick: 211,
    draft_year: 2018,
    player_id: 25697,
    profile_url: "http://www.vhlru.ru/en/players/25697/",
    league: "VHL",
    ep_url: "https://www.eliteprospects.com/player/420947/semyon-kizimov"
  }
]
