module.exports.prospects = [
  {
    first_name: "Fedor",
    last_name: "Gordeev",
    position: "D",
    shoots: "L",
    dob: "1999-01-27",
    player_id: 7146,
    profile_url: "http://cluster.leaguestat.com/feed/?feed=modulekit&view=player&key=f109cf290fcf50d4&fmt=json&client_code=ohl&lang=en&player_id=7146&category=seasonstats",
    league: "OHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=273797"
  },
  {
    first_name: "Eemeli",
    last_name: "Rasanen",
    position: "D",
    shoots: "R",
    dob: "1999-03-06",
    player_id: 7308,
    profile_url: "http://cluster.leaguestat.com/feed/?feed=modulekit&view=player&key=f109cf290fcf50d4&fmt=json&client_code=ohl&lang=en&player_id=7308&category=seasonstats",
    league: "OHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=302228"
  },
  {
    first_name: "Nicolas",
    last_name: "Mattinen",
    position: "D",
    shoots: "R",
    dob: "1998-03-05",
    player_id: 7107,
    profile_url: "http://cluster.leaguestat.com/feed/?feed=modulekit&view=player&key=f109cf290fcf50d4&fmt=json&client_code=ohl&lang=en&player_id=7107&category=seasonstats",
    league: "OHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=251744"
  },
  {
    first_name: "Keaton",
    last_name: "Middleton",
    position: "D",
    shoots: "L",
    dob: "1998-02-10",
    player_id: 6753,
    profile_url: "http://cluster.leaguestat.com/feed/?feed=modulekit&view=player&key=f109cf290fcf50d4&fmt=json&client_code=ohl&lang=en&player_id=6753&category=seasonstats",
    league: "OHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=249597"
  },
  {
    first_name: "Ryan",
    last_name: "McGregor",
    position: "C",
    shoots: "L",
    dob: "1999-01-29",
    player_id: 7117,
    profile_url: "http://cluster.leaguestat.com/feed/?feed=modulekit&view=player&key=f109cf290fcf50d4&fmt=json&client_code=ohl&lang=en&player_id=7117&category=seasonstats",
    league: "OHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=289231"
  },
  {
    first_name: "Timothy",
    last_name: "Liljegren",
    position: "D",
    shoots: "R",
    dob: "1999-04-20",
    player_id: 6893,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6893&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=224910"
  },
  {
    first_name: "Andreas",
    last_name: "Johnsson",
    position: "LW",
    shoots: "L",
    dob: "1994-11-21",
    player_id: 6382,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6382&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=43991"
  },
  {
    first_name: "Jeremy",
    last_name: "Bracco",
    position: "RW",
    shoots: "R",
    dob: "1997-03-17",
    player_id: 6891,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6891&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=197800"
  },
  {
    first_name: "Adam",
    last_name: "Brooks",
    position: "C",
    shoots: "L",
    dob: "1996-05-06",
    player_id: 6888,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6888&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=120202"
  },
  {
    first_name: "Dmytro",
    last_name: "Timashov",
    position: "LW",
    shoots: "L",
    dob: "1996-10-01",
    player_id: 6445,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6445&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=115161"
  },
  {
    first_name: "Kasperi",
    last_name: "Kapanen",
    position: "RW",
    shoots: "R",
    dob: "1996-07-23",
    player_id: 5902,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=5902&season_id=&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=92226"
  },
  {
    first_name: "Travis",
    last_name: "Dermott",
    position: "D",
    shoots: "L",
    dob: "1996-12-22",
    player_id: 6381,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6381&season_id=&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=214673"
  },
  {
    first_name: "Andrew",
    last_name: "Nielsen",
    position: "D",
    shoots: "L",
    dob: "1996-11-13",
    player_id: 6296,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6296&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=131262"
  },
  {
    first_name: "Calle",
    last_name: "Rosen",
    position: "D",
    shoots: "L",
    dob: "1994-02-02",
    player_id: 6917,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6917&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=37021"
  },
  {
    first_name: "Frederik",
    last_name: "Gauthier",
    position: "C",
    shoots: "L",
    dob: "1995-04-26",
    player_id: 5585,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=5585&season_id=&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=128500"
  },
  {
    first_name: "Andreas",
    last_name: "Borgman",
    position: "D",
    shoots: "L",
    dob: "1995-06-18",
    player_id: 6966,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6966&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=85683"
  },
  {
    first_name: "Miro",
    last_name: "Aaltonen",
    position: "C",
    shoots: "L",
    dob: "1993-06-07",
    player_id: 6892,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=6892&season_id=57&site_id=1&key=50c2cd9b5e18e390&client_code=ahl&league_id=&lang=en&statsType=standard&callback=json",
    league: "AHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=44162"
  },
  {
    first_name: "Martin",
    last_name: "Dzierkals",
    position: "LW",
    shoots: "L",
    dob: "1997-04-04",
    player_id: 7331,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7331&season_id=44&site_id=1&key=e18cfddba0db3b21&client_code=echl&league_id=&lang=en&statsType=standard&callback=json",
    league: "ECHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=239362"
  },
  {
    first_name: "J.J.",
    last_name: "Piccinich",
    position: "RW",
    shoots: "R",
    dob: "1996-06-12",
    player_id: 7137,
    profile_url: "https://lscluster.hockeytech.com/feed/index.php?feed=statviewfeed&view=player&player_id=7137&season_id=43&site_id=1&key=e18cfddba0db3b21&client_code=echl&league_id=&lang=en&statsType=standard&callback=json",
    league: "ECHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=191113"
  },
  {
    first_name: "Yegor",
    last_name: "Korshkov",
    position: "RW",
    shoots: "L",
    dob: "1996-07-10",
    player_id: 20766,
    profile_url: "https://en.khl.ru/players/20766/",
    league: "KHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=176637"
  },
  {
    first_name: "Carl",
    last_name: "Grundstrom",
    position: "LW",
    shoots: "L",
    dob: "1997-12-01",
    player_id: 0,
    profile_url: "https://www.shl.se/lag/087a-087aTQv9u__frolunda-hc/qQ9-3230HHhqE__carl-grundstrom/statistics",
    league: "SHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=113516"
  },
  {
    first_name: "Pierre",
    last_name: "Engvall",
    position: "LW/RW",
    shoots: "L",
    dob: "1996-05-31",
    player_id: 0,
    profile_url: "https://www.shl.se/lag/3db0-3db09jXTE__hv71/qRh-1LnWA7ztX__pierre-engvall/statistics",
    league: "SHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=147720"
  },
  {
    first_name: "Vladislav",
    last_name: "Kara",
    position: "C",
    shoots: "L",
    dob: "1998-04-20",
    player_id: 22888,
    profile_url: "http://www.vhlru.ru/en/players/22888/#c",
    league: "VHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=322627"
  },
  {
    first_name: "Nikolai",
    last_name: "Chebykin",
    position: "LW/RW",
    shoots: "L",
    dob: "1997-08-01",
    player_id: 22161,
    profile_url: "http://www.vhlru.ru/en/players/22161/#c",
    league: "VHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=300931"
  },
  {
    first_name: "Vladimir",
    last_name: "Bobylev",
    position: "LW/RW",
    shoots: "L",
    dob: "1997-04-18",
    player_id: 21313,
    profile_url: "https://engmhl.khl.ru/players/21313/",
    league: "VHL",
    ep_url: "http://www.eliteprospects.com/player.php?player=268059"
  },
  {
    first_name: "Dakota",
    last_name: "Joshua",
    position: "C",
    shoots: "L",
    dob: "1996-05-15",
    player_id: 29891,
    profile_url: "https://www.collegehockeynews.com/players/career/Dakota-Joshua/29891",
    league: "NCAA",
    ep_url: "http://www.eliteprospects.com/player.php?player=194948"
  },
  {
    first_name: "Nolan",
    last_name: "Vesey",
    position: "LW",
    shoots: "L",
    dob: "1995-03-28",
    player_id: 29532,
    profile_url: "https://www.collegehockeynews.com/players/career/Nolan-Vesey/29532",
    league: "NCAA",
    ep_url: "http://www.eliteprospects.com/player.php?player=248373"
  },
  {
    first_name: "James",
    last_name: "Greenway",
    position: "D",
    shoots: "L",
    dob: "1998-04-27",
    player_id: 31877,
    profile_url: "https://www.collegehockeynews.com/players/career/JD-Greenway/31877",
    league: "NCAA",
    ep_url: "http://www.eliteprospects.com/player.php?player=226438"
  },
  {
    first_name: "Jesper",
    last_name: "Lindgren",
    position: "D",
    shoots: "R",
    dob: "1997-05-19",
    player_id: 100025980,
    profile_url: "http://liiga.fi/pelaajat/100025980/lindgren-jesper",
    league: "Liiga",
    ep_url: "http://www.eliteprospects.com/player.php?player=187806"
  }
]
